# Generated by Django 3.1 on 2020-09-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='SOME STRING', max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, default='SOME STRING', max_length=255, null=True),
        ),
    ]
