# Generated by Django 3.1 on 2020-09-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_auto_20200902_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_class',
        ),
    ]
