# Generated by Django 3.1 on 2020-09-03 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_user_id'),
        ('subject', '0010_auto_20200903_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='teacher.teacher'),
        ),
    ]
