# Generated by Django 3.1 on 2020-08-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=2)),
                ('teacher_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('work_type', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_salary', models.FloatField(blank=True, null=True)),
                ('special_for', models.CharField(blank=True, max_length=255, null=True)),
                ('educational_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('special_training', models.CharField(blank=True, max_length=255, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('index_number', models.IntegerField(blank=True, null=True)),
                ('mpo_date', models.DateField(blank=True, null=True)),
                ('staff_id_no', models.IntegerField(blank=True, null=True)),
                ('staff_access', models.CharField(blank=True, choices=[('1', 'Teacher'), ('2', 'Staff')], max_length=2, null=True)),
                ('teacher_email', models.EmailField(max_length=255, null=True)),
                ('teacher_password', models.CharField(max_length=255, null=True)),
                ('teacher_phone', models.IntegerField(blank=True, null=True)),
                ('teacher_dob', models.DateField(null=True)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('passport', models.CharField(blank=True, max_length=100, null=True)),
                ('nid', models.IntegerField(null=True)),
                ('last_organizing', models.CharField(blank=True, max_length=255, null=True)),
                ('cause_of_leave', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_address', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.CharField(blank=True, max_length=255, null=True)),
                ('union', models.CharField(blank=True, max_length=255, null=True)),
                ('upozilla', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('permanent_village', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_post', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_union', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_upozilla', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_postal_code', models.IntegerField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('father_monthly_income', models.FloatField(blank=True, max_length=255, null=True)),
                ('father_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('father_phone', models.IntegerField(blank=True, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('father_nid', models.IntegerField(blank=True, null=True)),
                ('father_passport', models.CharField(blank=True, max_length=255, null=True)),
                ('father_license', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_monthly_income', models.FloatField(blank=True, max_length=255, null=True)),
                ('mother_educational_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_phone', models.IntegerField(blank=True, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('mother_nid', models.IntegerField(blank=True, null=True)),
                ('mother_passport', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_license', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('marrige_day', models.DateField(null=True)),
                ('spouse_education', models.CharField(blank=True, max_length=255, null=True)),
                ('kids', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
