# Generated by Django 3.1 on 2020-08-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='father_email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='father_license',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='father_monthly_income',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='father_nid',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='father_occupation',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='father_passport',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='father_phone',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='father_qualification',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='marrige_day',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mother_educational_qualification',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mother_email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mother_license',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mother_monthly_income',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mother_nid',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mother_occupation',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mother_passport',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mother_phone',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='spouse_education',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='spouse_occupation',
        ),
    ]
