# Generated by Django 3.1 on 2020-09-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user_id',
        ),
    ]
