# Generated by Django 3.1 on 2020-09-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
