# Generated by Django 3.1 on 2020-08-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=255, null=True)),
                ('student_name', models.CharField(max_length=255, null=True)),
                ('sex', models.CharField(max_length=20, null=True)),
                ('student_class', models.CharField(max_length=20, null=True)),
                ('shift', models.CharField(max_length=50, null=True)),
                ('section', models.CharField(max_length=50, null=True)),
                ('group', models.CharField(max_length=255, null=True)),
                ('id_number', models.IntegerField(blank=True, max_length=255, null=True)),
                ('class_roll', models.IntegerField(blank=True, max_length=100, null=True)),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_id_number', models.IntegerField(max_length=100, null=True)),
                ('phone_number', models.IntegerField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('old_school_address', models.CharField(blank=True, max_length=255, null=True)),
                ('cause_for_leave', models.CharField(blank=True, max_length=255, null=True)),
                ('house_no', models.CharField(blank=True, max_length=255, null=True)),
                ('house_name', models.CharField(blank=True, max_length=255, null=True)),
                ('road_no', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.CharField(blank=True, max_length=255, null=True)),
                ('union', models.CharField(blank=True, max_length=255, null=True)),
                ('upozilla', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.IntegerField(blank=True, max_length=20, null=True)),
                ('permanent_village', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_post', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_union', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_upozilla', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_postal_code', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
