# Generated by Django 3.1 on 2020-08-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_roll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
