# Generated by Django 3.1 on 2020-08-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200822_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='image',
            new_name='student_image',
        ),
    ]
