# Generated by Django 3.1 on 2020-09-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200827_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
    ]
