# Generated by Django 3.1 on 2020-09-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_remove_subject_subject_class'),
        ('student', '0010_remove_student_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ManyToManyField(null=True, to='subject.Class'),
        ),
    ]
