# Generated by Django 3.1 on 2020-09-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20200902_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_id',
            new_name='clases',
        ),
    ]
