# Generated by Django 3.1 on 2020-09-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20200902_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='clases',
            new_name='student_class',
        ),
    ]
