# Generated by Django 3.1.1 on 2020-09-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='active_status',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
