# Generated by Django 3.1.1 on 2020-09-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='role',
        ),
    ]
