# Generated by Django 3.1.1 on 2020-09-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20200909_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='apply_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='from_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='to_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
