# Generated by Django 3.1.1 on 2020-09-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20200909_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='active_status',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
