# Generated by Django 3.1.1 on 2020-09-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leavetype_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
