# Generated by Django 3.1.1 on 2020-09-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcard', '0003_auto_20200913_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentidcard',
            name='user_photo',
        ),
        migrations.AlterField(
            model_name='studentidcard',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='idcard/'),
        ),
        migrations.AlterField(
            model_name='studentidcard',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='idcard/'),
        ),
        migrations.AlterField(
            model_name='studentidcard',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='idcard/'),
        ),
    ]
