# Generated by Django 3.1.1 on 2020-09-13 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idcard', '0005_auto_20200913_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentidcard',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idcard.idcard'),
        ),
    ]
