# Generated by Django 3.1.1 on 2020-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcard', '0006_studentidcard_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentidcard',
            name='student_photo',
            field=models.ImageField(null=True, upload_to='studentidcard/'),
        ),
    ]
