# Generated by Django 3.1.1 on 2020-09-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcard', '0007_auto_20200913_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentidcard',
            name='student_photo',
        ),
    ]
