# Generated by Django 3.1.1 on 2020-09-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcard', '0008_remove_studentidcard_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentidcard',
            name='name',
        ),
    ]
