# Generated by Django 3.1.1 on 2020-09-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcard', '0009_remove_studentidcard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentidcard',
            name='id_side',
            field=models.CharField(choices=[('F', 'Front Side'), ('B', 'Back Side')], max_length=2, null=True),
        ),
    ]
