# Generated by Django 3.1.1 on 2020-09-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcard', '0010_studentidcard_id_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='valid_till',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
