# Generated by Django 3.1.1 on 2020-09-14 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcard', '0011_idcard_valid_till'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentidcard',
            old_name='student_id',
            new_name='user_id',
        ),
    ]
