# Generated by Django 3.1.1 on 2020-09-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcard', '0012_auto_20200914_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentidcard',
            name='type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('staff', 'Staff'), ('student', 'Student')], max_length=20, null=True),
        ),
    ]
