# Generated by Django 3.1.1 on 2020-09-09 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import frontoffice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonecalllog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('call_duration', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('followup', models.DateField(blank=True, null=True)),
                ('call_type', models.IntegerField(choices=[(1, 'Incoming'), (2, 'Outgoing')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postaldispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=200, null=True)),
                ('sender', models.CharField(max_length=200, null=True)),
                ('referance', models.CharField(max_length=200, null=True)),
                ('dispatch_date', models.DateField(null=True)),
                ('address', models.TextField(null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='postal', validators=[frontoffice.models.validate_file])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postalreceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=200, null=True)),
                ('sender', models.CharField(max_length=200, null=True)),
                ('referance', models.CharField(max_length=200, null=True)),
                ('receive_date', models.DateField(null=True)),
                ('address', models.TextField(null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='postal', validators=[frontoffice.models.validate_file])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitorbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('id_card', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('in_time', models.TimeField(null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='visitorbook', validators=[frontoffice.models.validate_file])),
                ('image', models.ImageField(null=True, upload_to='visitorbook', validators=[frontoffice.models.validate_image])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('meet_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meet_user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_type', models.CharField(choices=[('Fees', 'Fees'), ('Study', 'Study'), ('Teacher', 'Teacher'), ('Sports', 'Sports'), ('Transport', 'Transport'), ('Hostel', 'Hostel'), ('Front Site', 'Front Site'), ('Others', 'Others')], max_length=100, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='postal', validators=[frontoffice.models.validate_file])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('complain_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
