# Generated by Django 3.1.1 on 2020-09-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0002_auto_20200909_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='active_status',
            field=models.IntegerField(choices=[('0', 'Deleted'), ('2', 'Active')], default=2, null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='site_domain',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='site_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='phonecalllog',
            name='active_status',
            field=models.IntegerField(choices=[('0', 'Deleted'), ('2', 'Active')], default=2, null=True),
        ),
        migrations.AddField(
            model_name='phonecalllog',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='phonecalllog',
            name='site_domain',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='phonecalllog',
            name='site_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='postaldispatch',
            name='active_status',
            field=models.IntegerField(choices=[('0', 'Deleted'), ('2', 'Active')], default=2, null=True),
        ),
        migrations.AddField(
            model_name='postaldispatch',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='postaldispatch',
            name='site_domain',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='postaldispatch',
            name='site_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='postalreceive',
            name='active_status',
            field=models.IntegerField(choices=[('0', 'Deleted'), ('2', 'Active')], default=2, null=True),
        ),
        migrations.AddField(
            model_name='postalreceive',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='postalreceive',
            name='site_domain',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='postalreceive',
            name='site_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visitorbook',
            name='active_status',
            field=models.IntegerField(choices=[('0', 'Deleted'), ('2', 'Active')], default=2, null=True),
        ),
        migrations.AddField(
            model_name='visitorbook',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visitorbook',
            name='site_domain',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='visitorbook',
            name='site_id',
            field=models.IntegerField(null=True),
        ),
    ]
