# Generated by Django 3.1.1 on 2020-09-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0004_auto_20200909_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecalllog',
            name='followup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
