# Generated by Django 3.1.1 on 2020-09-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0005_auto_20200909_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='site_domain',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='phonecalllog',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='phonecalllog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='phonecalllog',
            name='site_domain',
        ),
        migrations.RemoveField(
            model_name='phonecalllog',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='postaldispatch',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='postaldispatch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='postaldispatch',
            name='site_domain',
        ),
        migrations.RemoveField(
            model_name='postaldispatch',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='postalreceive',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='postalreceive',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='postalreceive',
            name='site_domain',
        ),
        migrations.RemoveField(
            model_name='postalreceive',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='visitorbook',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='visitorbook',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='visitorbook',
            name='site_domain',
        ),
        migrations.RemoveField(
            model_name='visitorbook',
            name='site_id',
        ),
    ]
