# Generated by Django 3.1.1 on 2020-09-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0006_auto_20200909_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='active_status',
            field=models.IntegerField(blank=True, choices=[('0', 'Deleted'), ('2', 'Active')], default=2, null=True),
        ),
    ]
