# Generated by Django 3.1.1 on 2020-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0007_auto_20200909_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecalllog',
            name='active_status',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='postaldispatch',
            name='active_status',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='postalreceive',
            name='active_status',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='visitorbook',
            name='active_status',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='active_status',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
