# Generated by Django 3.1.1 on 2020-09-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0008_auto_20200909_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaldispatch',
            name='dispatch_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
